import type { DaySession, WarmupExercise, StretchExercise, Quote } from '@/types'

// ─── Warmup Protocols ────────────────────────────────────────────────────────

const PUSH_WARMUP: WarmupExercise[] = [
  {
    name: 'March in place + arm swings',
    duration: '90s',
    durationSecs: 90,
    joints: 'Full body · Heart + circulation',
    how: 'March lifting knees to hip height. Simultaneously swing arms forward and back, gradually increasing pace. Breathe through your nose.',
    tip: 'Core temp must be up before any pressing. Never skip this.',
  },
  {
    name: 'Wrist circles — both directions',
    duration: '30s',
    durationSecs: 30,
    joints: 'Wrist · Radioulnar',
    how: 'Make fists. Circle slowly clockwise 10×, then counter-clockwise 10×. Both wrists together.',
    tip: 'Crucial prep for bench press and overhead press — prevents wrist strain under load.',
  },
  {
    name: 'Shoulder CARs',
    duration: '45s',
    durationSecs: 45,
    joints: 'Glenohumeral · Scapulothoracic',
    how: 'Slow, deliberate full circles. Forward 5×, backward 5×. Feel every degree of range. Move from the shoulder blade, not just the arm.',
    tip: 'Full shoulder ROM before pressing. If anything catches or clicks, move more slowly through that range.',
  },
  {
    name: 'Thoracic rotation — hands behind head',
    duration: '45s',
    durationSecs: 45,
    joints: 'T1–T12 · Thoracic spine',
    how: 'Feet shoulder-width. Hands lightly behind head, elbows wide. Rotate upper back as far as you can, keeping hips forward. Pause 1s at end range. Drive from mid-back, not neck.',
    tip: 'Unlocks thoracic spine for overhead pressing. Most people are stuck here from sitting.',
  },
  {
    name: 'Band pull-aparts (or towel substitute)',
    duration: '40s — 2×15',
    durationSecs: 40,
    joints: 'Posterior shoulder · Rear delts · Rhomboids',
    how: 'Hold band or towel at shoulder width, arms straight. Pull apart horizontally to chest. Control return. Squeeze shoulder blades at the end position.',
    tip: 'Primes rear delts before pressing — prevents anterior shoulder impingement. Critical for posture.',
  },
  {
    name: 'Rotator cuff external rotation — light DB',
    duration: '35s — 2×10 each',
    durationSecs: 35,
    joints: 'Rotator cuff · Infraspinatus · Teres minor',
    how: 'Elbow pinned to side at 90°. Rotate forearm outward 10× each arm. Very light weight (2–4 kg). Slow and controlled.',
    tip: 'Protects rotator cuff under pressing load. Never skip on heavy bench or OHP days.',
  },
  {
    name: 'Scapular wall slides',
    duration: '35s — 2×10',
    durationSecs: 35,
    joints: 'Scapulothoracic · Serratus anterior · Lower traps',
    how: 'Back flat against wall, arms at 90°. Slide arms up (overhead) keeping back and wrists against wall. Squeeze shoulder blades down and together at the bottom.',
    tip: 'Sets scapular position before bench and OHP. If you can\'t touch the wall, your thoracic is stiff — keep working it.',
  },
]

const PULL_WARMUP: WarmupExercise[] = [
  {
    name: 'March in place + jumping jacks',
    duration: '90s',
    durationSecs: 90,
    joints: 'Full body · Heart rate elevation',
    how: 'March 30s, then jumping jacks for 60s. Increase pace through the 90s.',
    tip: 'Heart rate needs to be elevated before rows and pull-ups. Cold muscles under pulling load = high injury risk.',
  },
  {
    name: 'Neck CARs',
    duration: '40s',
    durationSecs: 40,
    joints: 'Cervical spine · C1–C7',
    how: 'Chin to chest → ear to shoulder → chin up → other side. Slow, deliberate circles. 5 each direction. Keep shoulders down throughout.',
    tip: 'Posture cue: imagine a string pulling the crown of your head upward as you circle.',
  },
  {
    name: 'Shoulder dislocates — towel wide grip',
    duration: '40s',
    durationSecs: 40,
    joints: 'Glenohumeral · Anterior shoulder · Thoracic',
    how: 'Hold towel wide (wider than shoulder width). Arms straight, raise over head and rotate behind you in a slow arc. If tight, widen grip. 10 reps.',
    tip: 'Opens anterior shoulder before rows. Do not force — widen grip until comfortable.',
  },
  {
    name: 'Dead hang — pull-up bar',
    duration: '2 × 20s',
    durationSecs: 40,
    joints: 'Shoulder · Spine decompression · Grip',
    how: 'Hang completely relaxed. Let gravity stretch you. Breathe deep. 20s, drop, shake out hands, repeat.',
    tip: 'Decompresses spine, primes grip, stretches lats. This is the single best pull-day warmup exercise.',
  },
  {
    name: 'Band face pulls or rear delt stretch',
    duration: '40s — 2×15',
    durationSecs: 40,
    joints: 'Rear delts · External rotators · Rhomboids',
    how: 'Face pull: rope to forehead, elbows high and wide. OR: cross arm across chest, other hand pulls at elbow for rear delt stretch, 30s each side.',
    tip: 'Primes rear delts and external rotators before heavy pulling. Builds the shoulder health foundation.',
  },
  {
    name: 'Scapular pull-ups',
    duration: '35s — 2×10',
    durationSecs: 35,
    joints: 'Scapulothoracic · Lower traps · Serratus',
    how: 'Hang from bar. Without bending elbows, depress and retract shoulder blades — body rises slightly. Hold 1s. Release. That\'s one rep.',
    tip: 'Activates the exact muscles that stabilize your shoulder blades during rows and pull-ups. Non-negotiable.',
  },
]

const LEGS_WARMUP: WarmupExercise[] = [
  {
    name: 'March in place + arm swings',
    duration: '2 min',
    durationSecs: 120,
    joints: 'Full body · Core temperature',
    how: 'March lifting knees high, arms swinging opposite to legs. Gradually increase pace over 2 minutes.',
    tip: 'Core temperature must be elevated before any joint-specific work — especially important for the knee.',
  },
  {
    name: 'Hip circles — each leg each direction',
    duration: '45s — 10 each',
    durationSecs: 45,
    joints: 'Hip · Acetabulum · Femoral head',
    how: 'Stand on one leg (hold wall if needed). Draw large circles with raised knee — forward, out, back, in. Full ROM. 10 each direction, each leg.',
    tip: 'Primes the hip capsule. Most important leg warmup movement. Cold hips = knee compensation.',
  },
  {
    name: 'Knee circles — feet together, both directions',
    duration: '30s',
    durationSecs: 30,
    joints: 'Knee · Patellofemoral · Synovial fluid',
    how: 'Feet together, hands on knees. Draw circles with both knees — 10 clockwise, 10 counter-clockwise. Slow and deliberate.',
    tip: 'Distributes synovial fluid around the patella before any loading. Critical for your knee health protocol.',
  },
  {
    name: 'Ankle CARs — lift foot, trace full circles',
    duration: '40s — 10 each foot',
    durationSecs: 40,
    joints: 'Ankle · Subtalar · Talocrural',
    how: 'Lift one foot. Trace the largest possible circles with your toes — clockwise 10×, counter-clockwise 10×. Switch feet.',
    tip: 'Critical for flat foot — improves squat depth over time. The range will increase week by week.',
  },
  {
    name: 'Calf raises — bodyweight, full ROM',
    duration: '30s — 15 reps',
    durationSecs: 30,
    joints: 'Ankle · Gastrocnemius · Soleus',
    how: 'Stand on edge of step or flat ground. Lower heel fully, rise to full tiptoe. Slow, controlled. 15 reps.',
    tip: 'Ankle warm-up and flat foot correction. The heel-drop ROM is the key movement for your flat foot.',
  },
  {
    name: 'Glute bridges — bodyweight',
    duration: '45s — 2×15, 2s squeeze',
    durationSecs: 45,
    joints: 'Glutes · Posterior chain · Lumbar stabilization',
    how: 'Lie on back, feet flat, knees bent. Drive hips up, squeeze glutes hard at top. Hold 2 seconds. Lower with control. Full hip extension — don\'t just lift hips, extend them.',
    tip: 'Cold glutes = lower back compensation on squats and deadlifts. This is non-negotiable knee protection.',
  },
  {
    name: 'Leg swings front/back',
    duration: '35s — 15 each leg',
    durationSecs: 35,
    joints: 'Hip flexion/extension · Hamstrings',
    how: 'Hold wall. Swing leg forward and back with control, gradually increasing amplitude. Keep swing controlled, not floppy. 15 reps each leg.',
    tip: 'Dynamic, not ballistic. Control through the full arc.',
  },
  {
    name: 'Lateral leg swings',
    duration: '35s — 15 each leg',
    durationSecs: 35,
    joints: 'Adductors · Abductors · Hip IR/ER',
    how: 'Hold wall. Swing leg across body and out to the side. Increasing amplitude. 15 reps each leg.',
    tip: 'Opens adductors and abductors before squatting. Addresses the ankle stability and hip mobility combination.',
  },
]

// ─── Stretch Protocols ────────────────────────────────────────────────────────

const PUSH_STRETCH: StretchExercise[] = [
  { name: 'Chest doorway stretch', duration: '30s × 2 sides', durationSecs: 60 },
  { name: 'Cross-body shoulder stretch', duration: '30s each arm', durationSecs: 60 },
  { name: 'Overhead tricep stretch', duration: '30s each arm', durationSecs: 60 },
  { name: "Child's pose (modified — no deep knee bend)", duration: '45s', durationSecs: 45 },
]

const PULL_STRETCH: StretchExercise[] = [
  { name: 'Lat stretch — arm overhead, lean sideways', duration: '30s each side', durationSecs: 60 },
  { name: 'Bicep wall stretch', duration: '30s each arm', durationSecs: 60 },
  { name: 'Cat-cow — 10 slow reps', duration: '~60s', durationSecs: 60 },
  { name: 'Thread-the-needle thoracic rotation', duration: '20s each side', durationSecs: 40 },
]

const LEGS_STRETCH: StretchExercise[] = [
  { name: 'Standing quad stretch — wall support, no kneeling', duration: '30s each leg', durationSecs: 60 },
  { name: 'Lying hamstring stretch — on back, pull leg up', duration: '30s each leg', durationSecs: 60 },
  { name: 'Figure-4 glute stretch — lying on back', duration: '40s each side', durationSecs: 80 },
  { name: 'Calf wall stretch — straight leg (gastrocnemius)', duration: '30s each', durationSecs: 60 },
  { name: 'Calf wall stretch — bent knee (soleus)', duration: '30s each', durationSecs: 60 },
]

// ─── Day Sessions ─────────────────────────────────────────────────────────────

export const PUSH_A: DaySession = {
  dayType: 'push_a',
  label: 'Push A',
  focus: 'Chest Primary',
  warmupProtocol: 'push',
  warmupDurationMins: 8,
  warmup: PUSH_WARMUP,
  stretch: PUSH_STRETCH,
  exercises: [
    {
      name: 'Barbell Bench Press',
      sets: 3,
      reps: '6–8',
      restSecs: 150,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 40,
      notes: 'Scapulae retracted and depressed throughout. Controlled 2s descent. No elbow lockout.',
      alternatives: ['Smith Machine Bench'],
      muscleGroups: ['chest', 'shoulders', 'triceps'],
    },
    {
      name: 'Incline DB Press',
      sets: 3,
      reps: '10–12',
      restSecs: 90,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 14,
      notes: '30–45° incline. Upper chest shelf — critical for V-taper aesthetics.',
      alternatives: ['Incline Smith Press'],
      muscleGroups: ['chest', 'shoulders'],
    },
    {
      name: 'Cable Fly — Low Cable Cross',
      sets: 3,
      reps: '12–15',
      restSecs: 75,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 7.5,
      notes: 'Full pec stretch at open. Hard squeeze at close. Chest only, not shoulders.',
      alternatives: ['Pec Deck Machine'],
      muscleGroups: ['chest'],
    },
    {
      name: 'Dip — Assisted Machine',
      sets: 3,
      reps: 'AMRAP',
      restSecs: 120,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 40,
      isAssistance: true,
      notes: 'Chest-forward lean. Lower to 90°. Log the assistance weight (kg). Reduce it as strength builds.',
      alternatives: ['Parallel bar dip BW'],
      muscleGroups: ['chest', 'triceps', 'shoulders'],
    },
    {
      name: 'DB Lateral Raises',
      sets: 3,
      reps: '15',
      restSecs: 60,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 6,
      notes: 'Medial delt — the muscle that creates shoulder width. Slight forward lean, pinky up, stop at shoulder height.',
      alternatives: ['Cable Lateral Raise'],
      muscleGroups: ['shoulders'],
    },
    {
      name: 'Plank',
      sets: 2,
      reps: '45–60s',
      restSecs: 45,
      isTimed: true,
      durationSecs: 52,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 0,
      notes: 'Glutes squeezed, hips level. Full countdown timer in app.',
      alternatives: ['Dead Bug'],
      muscleGroups: ['core'],
    },
  ],
}

export const PULL_A: DaySession = {
  dayType: 'pull_a',
  label: 'Pull A',
  focus: 'Back Width + Lats',
  warmupProtocol: 'pull',
  warmupDurationMins: 8,
  warmup: PULL_WARMUP,
  stretch: PULL_STRETCH,
  exercises: [
    {
      name: 'Barbell Bent-Over Row',
      sets: 3,
      reps: '6–8',
      restSecs: 150,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 40,
      notes: 'Hip hinge, neutral spine. Pull bar to lower chest. Elbows track back. Primary compound.',
      alternatives: ['Chest-Supported DB Row'],
      muscleGroups: ['back', 'biceps'],
    },
    {
      name: 'Assisted Pull-up — Overhand Wide',
      sets: 3,
      reps: 'AMRAP',
      restSecs: 120,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 40,
      isAssistance: true,
      notes: 'Full dead hang bottom. Chin over bar top. Log the assistance weight (kg) — reduce it as strength builds.',
      alternatives: ['Wide-Grip Lat Pulldown'],
      muscleGroups: ['back', 'biceps'],
    },
    {
      name: 'Lat Pulldown — Wide Grip',
      sets: 3,
      reps: '10–12',
      restSecs: 90,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 30,
      notes: 'Pull elbows to back pockets. Squeeze lats. Supplemental to pull-ups — same movement pattern.',
      alternatives: ['Straight-Arm Cable Pulldown'],
      muscleGroups: ['back'],
    },
    {
      name: 'Seated Cable Row — Close Grip',
      sets: 3,
      reps: '10–12',
      restSecs: 90,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 30,
      notes: 'Rhomboids and mid-trap. Pause 1s at chest. Posture anchor.',
      alternatives: ['Low Row Machine'],
      muscleGroups: ['back'],
    },
    {
      name: 'DB Bicep Curl',
      sets: 3,
      reps: '10–12',
      restSecs: 75,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 10,
      notes: '3s eccentric. Elbows pinned. No body swing.',
      alternatives: ['EZ Bar Curl'],
      muscleGroups: ['biceps'],
    },
    {
      name: 'Wrist Curls — Both Directions',
      sets: 2,
      reps: '15–20',
      restSecs: 30,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 4,
      notes: 'Palms up then palms down. Very light. Forearm and wrist rehab, not strength work.',
      alternatives: ['Reverse Curl Light'],
      muscleGroups: ['forearms'],
    },
  ],
}

export const LEGS_A: DaySession = {
  dayType: 'legs_a',
  label: 'Legs A',
  focus: 'Quad-Dominant, Knee-Safe',
  warmupProtocol: 'legs',
  warmupDurationMins: 10,
  warmup: LEGS_WARMUP,
  stretch: LEGS_STRETCH,
  exercises: [
    {
      name: 'Goblet Squat',
      sets: 4,
      reps: '10–12',
      restSecs: 90,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 12,
      notes: 'DB at chest. Sit between knees. Pain-free depth only — build depth gradually as ankle mobility improves.',
      alternatives: ['Leg Press Only'],
      muscleGroups: ['quads', 'glutes'],
    },
    {
      name: 'Leg Press',
      sets: 3,
      reps: '12–15',
      restSecs: 90,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 50,
      notes: 'Mid-foot on platform. Stop 10° before full extension. Never lock knees.',
      alternatives: ['Hack Squat'],
      muscleGroups: ['quads', 'glutes'],
    },
    {
      name: 'DB Romanian Deadlift',
      sets: 3,
      reps: '10–12',
      restSecs: 90,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 15,
      notes: 'Hip hinge, slight knee bend, neutral back. Stretch hamstrings fully at bottom. Knee-safe pattern.',
      alternatives: ['Cable Pull-Through'],
      muscleGroups: ['hamstrings', 'glutes'],
    },
    {
      name: 'Leg Extension — PARTIAL 0 to 90° ONLY',
      sets: 2,
      reps: '15',
      restSecs: 75,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: true,
      defaultWeightKg: 20,
      notes: 'Hard stop at 90°. Never past. Knee protocol — non-negotiable. Strengthens quad without patellar stress.',
      alternatives: ['Terminal Knee Extension Cable'],
      muscleGroups: ['quads'],
    },
    {
      name: 'Seated Calf Raises',
      sets: 4,
      reps: '15–20',
      restSecs: 45,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 10,
      notes: 'Heel below platform at bottom (full stretch). Tiptoe at top. Soleus focus — helps flat foot correction.',
      alternatives: ['Leg Press Calf Press'],
      muscleGroups: ['calves'],
    },
    {
      name: 'Kegels',
      sets: 3,
      reps: '10 holds × 10s',
      restSecs: 30,
      isTimed: true,
      durationSecs: 10,
      isUnilateral: false,
      isMandatory: true,
      hasKneeWarning: false,
      defaultWeightKg: 0,
      notes: 'Squeeze and hold 10s, release fully. Pelvic floor and deep core. Mandatory — cannot be removed.',
      alternatives: [],
      muscleGroups: ['core'],
    },
    {
      name: 'Lying Leg Raises',
      sets: 2,
      reps: '15',
      restSecs: 45,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 0,
      notes: 'Hands under hips. Slow descent. No lower back arch.',
      alternatives: ['Hanging Knee Raise'],
      muscleGroups: ['core'],
    },
  ],
}

export const PUSH_B: DaySession = {
  dayType: 'push_b',
  label: 'Push B',
  focus: 'Shoulder Primary',
  warmupProtocol: 'push',
  warmupDurationMins: 8,
  warmup: PUSH_WARMUP,
  stretch: PUSH_STRETCH,
  exercises: [
    {
      name: 'Overhead Press — Barbell or Smith',
      sets: 3,
      reps: '6–8',
      restSecs: 150,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 30,
      notes: 'Core braced hard. No lumbar hyperextension. Primary compound. Builds the shoulder-dominant physique.',
      alternatives: ['DB Shoulder Press Seated'],
      muscleGroups: ['shoulders', 'triceps'],
    },
    {
      name: 'Incline Barbell Press',
      sets: 3,
      reps: '8–10',
      restSecs: 90,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 35,
      notes: 'Different angle from Monday. Upper chest and front delt. Builds the chest-shoulder tie-in.',
      alternatives: ['Incline DB Press'],
      muscleGroups: ['chest', 'shoulders'],
    },
    {
      name: 'Pec Deck Fly',
      sets: 3,
      reps: '12–15',
      restSecs: 75,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 20,
      notes: 'Different angle and feel from cable fly Monday. Squeeze at close — pecs only.',
      alternatives: ['Cable Fly Crossover'],
      muscleGroups: ['chest'],
    },
    {
      name: 'Dip — Assisted Machine',
      sets: 3,
      reps: 'AMRAP',
      restSecs: 120,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 40,
      isAssistance: true,
      notes: 'Same as Monday. Track progress — log the assistance weight (kg) and reduce it as strength improves.',
      alternatives: ['BW Dip'],
      muscleGroups: ['chest', 'triceps', 'shoulders'],
    },
    {
      name: 'Tricep Pushdown — Rope',
      sets: 3,
      reps: '12–15',
      restSecs: 75,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 15,
      notes: 'Elbows pinned to sides. Spread rope at bottom, hard squeeze. Direct tricep isolation after dips.',
      alternatives: ['V-Bar Pushdown'],
      muscleGroups: ['triceps'],
    },
    {
      name: 'DB Lateral Raises',
      sets: 3,
      reps: '15',
      restSecs: 60,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 6,
      notes: 'Same as Monday. Medial delt twice per week = faster shoulder width development.',
      alternatives: ['Cable Lateral Raise'],
      muscleGroups: ['shoulders'],
    },
  ],
}

export const PULL_B: DaySession = {
  dayType: 'pull_b',
  label: 'Pull B',
  focus: 'Back Thickness + Arms + Forearms',
  warmupProtocol: 'pull',
  warmupDurationMins: 8,
  warmup: PULL_WARMUP,
  stretch: PULL_STRETCH,
  exercises: [
    {
      name: 'T-Bar Row or Chest-Supported DB Row',
      sets: 3,
      reps: '8–10',
      restSecs: 150,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 25,
      notes: 'Mid-back density. Different pull angle from Tuesday.',
      alternatives: ['Barbell Bent-Over Row'],
      muscleGroups: ['back'],
    },
    {
      name: 'Assisted Chin-up — Underhand',
      sets: 3,
      reps: 'AMRAP',
      restSecs: 120,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 40,
      isAssistance: true,
      notes: 'Underhand = more bicep contribution than Tuesday overhand. Log the assistance weight (kg) — reduce it as strength builds.',
      alternatives: ['Underhand Lat Pulldown'],
      muscleGroups: ['back', 'biceps'],
    },
    {
      name: 'Single-Arm DB Row',
      sets: 3,
      reps: '10–12',
      restSecs: 90,
      isTimed: false,
      isUnilateral: true,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 12,
      notes: 'Full ROM. Unilateral — logs L/R separately, flags imbalance if gap >10% across 3+ sessions.',
      alternatives: ['Single-Arm Cable Row'],
      muscleGroups: ['back'],
    },
    {
      name: 'Face Pulls — Cable Rope',
      sets: 3,
      reps: '15',
      restSecs: 75,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 10,
      notes: 'Rope to forehead, elbows high and wide. Rear delt + external rotation. Most important shoulder health exercise.',
      alternatives: ['Band Face Pull'],
      muscleGroups: ['shoulders', 'back'],
    },
    {
      name: 'Hammer Curl',
      sets: 2,
      reps: '12',
      restSecs: 75,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 10,
      notes: 'Neutral grip. Brachialis and brachioradialis. Makes arms look thicker from the side.',
      alternatives: ['Rope Hammer Curl'],
      muscleGroups: ['biceps', 'forearms'],
    },
    {
      name: 'Reverse Curl — EZ Bar',
      sets: 2,
      reps: '15',
      restSecs: 45,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 8,
      notes: 'Overhand grip. Directly targets the forearm visual gap.',
      alternatives: ['Reverse Cable Curl'],
      muscleGroups: ['forearms', 'biceps'],
    },
    {
      name: 'Wrist Curls — Both Directions',
      sets: 2,
      reps: '15–20',
      restSecs: 30,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 4,
      notes: 'Very light. Palms up, then palms down. Forearm balance and wrist rehab.',
      alternatives: [],
      muscleGroups: ['forearms'],
    },
  ],
}

export const LEGS_B: DaySession = {
  dayType: 'legs_b',
  label: 'Legs B',
  focus: 'Posterior Chain + Glutes + Calves',
  warmupProtocol: 'legs',
  warmupDurationMins: 10,
  warmup: LEGS_WARMUP,
  stretch: LEGS_STRETCH,
  exercises: [
    {
      name: 'Barbell Romanian Deadlift',
      sets: 4,
      reps: '8–10',
      restSecs: 150,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 50,
      notes: 'Highest testosterone-stimulating lift in this program. Hip hinge — push hips back, not down. Hamstrings stretch at bottom. Neutral spine mandatory.',
      alternatives: ['DB Romanian Deadlift'],
      muscleGroups: ['hamstrings', 'glutes', 'back'],
    },
    {
      name: 'Smith Machine Squat',
      sets: 3,
      reps: '10–12',
      restSecs: 90,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 40,
      notes: 'Feet slightly forward of bar. Controlled depth — knee-safe. More stable than barbell squat while technique develops.',
      alternatives: ['Hack Squat Machine'],
      muscleGroups: ['quads', 'glutes'],
    },
    {
      name: 'Bulgarian Split Squat — DB',
      sets: 3,
      reps: '10',
      restSecs: 90,
      isTimed: false,
      isUnilateral: true,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 10,
      notes: 'Rear foot elevated on bench. Most effective unilateral leg exercise — addresses L/R imbalance. Log each leg separately.',
      alternatives: ['Reverse Lunge'],
      muscleGroups: ['quads', 'glutes'],
    },
    {
      name: 'Prone Leg Curl',
      sets: 3,
      reps: '12–15',
      restSecs: 75,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 20,
      notes: '3s controlled eccentric. Hamstring isolation after RDL.',
      alternatives: ['Seated Leg Curl'],
      muscleGroups: ['hamstrings'],
    },
    {
      name: 'Standing Calf Raises',
      sets: 4,
      reps: '15–20',
      restSecs: 45,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 0,
      notes: 'Full ROM. 2 sets straight knee (gastrocnemius), 2 sets slight bend (soleus). Builds the calf thickness deficit.',
      alternatives: ['Leg Press Calf Raise'],
      muscleGroups: ['calves'],
    },
    {
      name: 'Kegels',
      sets: 3,
      reps: '10 holds × 10s',
      restSecs: 30,
      isTimed: true,
      durationSecs: 10,
      isUnilateral: false,
      isMandatory: true,
      hasKneeWarning: false,
      defaultWeightKg: 0,
      notes: 'Hold 10s, release fully. Mandatory.',
      alternatives: [],
      muscleGroups: ['core'],
    },
    {
      name: 'Russian Twists',
      sets: 2,
      reps: '15 each side',
      restSecs: 45,
      isTimed: false,
      isUnilateral: false,
      isMandatory: false,
      hasKneeWarning: false,
      defaultWeightKg: 0,
      notes: 'Feet flat — knee-friendly. BW first, add DB when form is solid.',
      alternatives: ['Cable Wood Chop'],
      muscleGroups: ['core'],
    },
  ],
}

// ─── Day Map ──────────────────────────────────────────────────────────────────

export const DAY_SESSIONS: Record<string, DaySession> = {
  push_a: PUSH_A,
  pull_a: PULL_A,
  legs_a: LEGS_A,
  push_b: PUSH_B,
  pull_b: PULL_B,
  legs_b: LEGS_B,
}

// Maps getDay() (0=Sun…6=Sat) to dayType. 0 = rest.
export const DAY_OF_WEEK_MAP: Record<number, string> = {
  0: 'rest',
  1: 'push_a',
  2: 'pull_a',
  3: 'legs_a',
  4: 'push_b',
  5: 'pull_b',
  6: 'legs_b',
}

export const ALL_SESSIONS = [PUSH_A, PULL_A, LEGS_A, PUSH_B, PULL_B, LEGS_B]

// ─── Muscle Group → Day Type Map (for heatmap) ────────────────────────────────

export const MUSCLE_DAY_MAP: Record<string, string[]> = {
  chest: ['push_a', 'push_b'],
  shoulders: ['push_a', 'push_b'],
  triceps: ['push_a', 'push_b'],
  back: ['pull_a', 'pull_b'],
  biceps: ['pull_a', 'pull_b'],
  forearms: ['pull_a', 'pull_b'],
  quads: ['legs_a', 'legs_b'],
  hamstrings: ['legs_a', 'legs_b'],
  glutes: ['legs_a', 'legs_b'],
  calves: ['legs_a', 'legs_b'],
  core: ['legs_a', 'legs_b', 'push_a'],
}

// ─── Universal Full-Body Warmup (10 min Override) ────────────────────────────
// 4 phases: Elevation → Joint circles → Hip mobility flow → Dynamic activation
// Always accessible as override from any day's warmup

export const FULL_BODY_WARMUP: WarmupExercise[] = [
  // Phase 1 — Elevation (2 min)
  {
    name: 'Marching in place with arm swings',
    duration: '2 min',
    durationSecs: 120,
    joints: 'Phase 1: Elevation · Full body · Heart + circulation',
    how: 'March lifting knees to hip height. Swing arms forward and back, gradually increasing pace. Breathe through your nose.',
    tip: 'Primes joint fluid before any rotational work — never skip this.',
  },
  // Phase 2 — Joint circles (3 min)
  {
    name: 'Neck CARs',
    duration: '40s',
    durationSecs: 40,
    joints: 'Phase 2: Joint circles · Cervical spine · C1–C7',
    how: 'Chin to chest → ear to shoulder → chin up → other side. Slow, deliberate circles. 5 each direction. Keep shoulders down.',
    tip: 'Imagine a string pulling the crown of your head upward as you circle.',
  },
  {
    name: 'Shoulder circles + arm swings',
    duration: '40s',
    durationSecs: 40,
    joints: 'Phase 2: Joint circles · Glenohumeral · Scapulothoracic',
    how: 'Small circles → large circles → full windmill swings. Cross both arms across chest 10×. Feel the scapula winging open.',
    tip: 'Include scapular circles: squeeze blades together, then pull them apart and around.',
  },
  {
    name: 'Wrist + elbow circles',
    duration: '25s',
    durationSecs: 25,
    joints: 'Phase 2: Joint circles · Wrist · Radioulnar · Elbow',
    how: 'Wrists: make fists, circle slowly both ways 10×. Elbow: flex/extend fully then pronate/supinate forearm 10× each arm.',
    tip: 'Crucial if you bench, overhead press, or do pull-ups.',
  },
  {
    name: 'Thoracic spine rotation (hands behind head)',
    duration: '45s',
    durationSecs: 45,
    joints: 'Phase 2: Joint circles · T1–T12 · Thoracic spine',
    how: 'Feet shoulder-width. Hands lightly behind head, elbows wide. Rotate upper back as far as possible, keeping hips forward. Pause 1s at end range. Drive from mid-back, not neck.',
    tip: 'Most people have stuck T-spine from desk work. This unlocks overhead pressing and posture.',
  },
  {
    name: 'Hip circles',
    duration: '40s',
    durationSecs: 40,
    joints: 'Phase 2: Joint circles · Hip · Acetabulum · Femoral head',
    how: 'Stand on one leg (hold wall if needed). Draw large circles with raised knee — forward, out, back, in. 10 each direction, each leg.',
    tip: 'Primes the hip capsule before the deeper mobility work in the next phase.',
  },
  {
    name: 'Knee circles + ankle rolls',
    duration: '30s',
    durationSecs: 30,
    joints: 'Phase 2: Joint circles · Knee · Patellofemoral · Ankle · Subtalar',
    how: 'Knees: feet together, hands on knees, draw circles both ways 10×. Ankles: lift one foot, trace full circles with toes 10×. Switch.',
    tip: 'Ankle mobility directly determines squat depth and knee safety.',
  },
  // Phase 3 — Hip mobility flow (3 min)
  {
    name: '90/90 hip flow (IR + ER)',
    duration: '70s',
    durationSecs: 70,
    joints: 'Phase 3: Hip mobility flow · Hip IR/ER · Piriformis · Psoas · Adductors',
    how: 'Sit on floor: front leg externally rotated, back leg internally rotated — both at 90°. Lean forward over front shin. Hold 5s at end range. Windshield-wiper to switch sides.',
    tip: 'The single most important hip mobility drill — targets IR and ER simultaneously, both halves most people never train.',
  },
  {
    name: "World's greatest stretch",
    duration: '60s',
    durationSecs: 60,
    joints: 'Phase 3: Hip mobility flow · Hip flexor · T-spine · Hamstring · Shoulder · Ankle',
    how: 'Step into deep lunge (right foot forward). Left hand on floor inside right foot. Rotate right arm up to ceiling, hold 3s. Drop elbow inside foot. Push back to hamstring stretch. Return to lunge. Switch sides.',
    tip: 'This single movement hits 6+ joints — used by elite athletes worldwide as a standalone drill.',
  },
  {
    name: 'Cat-cow + spinal segmentation',
    duration: '40s',
    durationSecs: 40,
    joints: 'Phase 3: Hip mobility flow · Lumbar spine · Thoracic spine · Cervical',
    how: 'On all fours, exhale → round spine fully (cat). Inhale → arch spine, chest forward, tail up (cow). Move segment by segment from tailbone up through lumbar, thoracic, then neck. 10 slow reps.',
    tip: 'Posture reset: this reverses hours of forward-flexion sitting.',
  },
  // Phase 4 — Dynamic activation (2 min)
  {
    name: 'Leg swings — front/back + lateral',
    duration: '40s',
    durationSecs: 40,
    joints: 'Phase 4: Dynamic activation · Hip flexion/extension · Adductors · Abductors',
    how: 'Hold a wall. Swing leg forward and back with control, gradually increasing amplitude. Then swing sideways. 15 reps each direction, each leg.',
    tip: 'Dynamic, not ballistic. Control through the full arc.',
  },
  {
    name: 'Glute bridge + hip thrust',
    duration: '40s',
    durationSecs: 40,
    joints: 'Phase 4: Dynamic activation · Glutes · Posterior chain · Lumbar stabilization',
    how: 'Lie on back, feet flat, knees bent. Drive hips up, squeeze glutes hard at top. Hold 2 seconds. Lower with control. Full hip extension — do not just lift hips, extend them.',
    tip: 'Activates glutes before squats/deadlifts. Cold glutes = lower back compensation.',
  },
  {
    name: 'Inchworm walkout',
    duration: '40s',
    durationSecs: 40,
    joints: 'Phase 4: Dynamic activation · Hamstrings · Shoulders · Wrists · Core',
    how: 'Stand, hinge forward, hands to floor. Walk hands out to plank. Do 1 shoulder tap each side. Walk hands back to feet. Stand up. 5 full walkouts, controlled.',
    tip: 'Ties everything together — full body integration before your lifts.',
  },
]

// ─── Motivational Quotes Fallback ─────────────────────────────────────────────

export const FALLBACK_QUOTES: Quote[] = [
  // Anime
  { text: 'Hard work is worthless for those that don\'t believe in themselves.', author: 'Naruto Uzumaki' },
  { text: 'Push through the pain, giving up hurts more.', author: 'Vegeta' },
  { text: 'If you don\'t take risks, you can\'t create a future.', author: 'Monkey D. Luffy' },
  { text: 'Power comes in response to a need, not a desire.', author: 'Goku' },
  { text: 'A dropout will beat a genius through hard work.', author: 'Rock Lee' },
  { text: 'We are all like fireworks: we climb, we shine, and always go our separate ways and become further apart. But even when that time comes, let\'s not disappear like a firework and continue to shine forever.', author: 'Hitsugaya Toshiro' },
  { text: 'If you don\'t like your destiny, don\'t accept it. Instead, have the courage to change it the way you want it to be.', author: 'Naruto Uzumaki' },
  { text: 'Knowing what it feels to be in pain is exactly why we try to be kind to others.', author: 'Jiraiya' },
  { text: 'Whatever you lose, you\'ll find it again. But what you throw away you\'ll never get back.', author: 'Kenshin Himura' },
  { text: 'A true warrior does not battle for its own sake. A true warrior battles for the sake of others.', author: 'Asta' },
  { text: 'The moment you think of giving up, think of the reason why you held on so long.', author: 'Natsu Dragneel' },
  { text: 'Don\'t give up. There\'s no shame in falling down. True shame is to not stand up again.', author: 'Shintaro Midorima' },
  { text: 'Simplicity is the easiest path to true beauty.', author: 'Seijuro Akashi' },
  { text: 'Fear is not evil. It tells you what your weakness is.', author: 'Gildarts Clive' },
  { text: 'Giving up is what kills people. When people reject giving up... they finally win.', author: 'Aokiji' },
  // Personality & Philosophy
  { text: 'The only bad workout is the one that didn\'t happen.', author: 'Unknown' },
  { text: 'Take care of your body. It\'s the only place you have to live.', author: 'Jim Rohn' },
  { text: 'The pain you feel today will be the strength you feel tomorrow.', author: 'Arnold Schwarzenegger' },
  { text: 'Success usually comes to those who are too busy to be looking for it.', author: 'Henry David Thoreau' },
  { text: 'All progress takes place outside the comfort zone.', author: 'Michael John Bobak' },
  { text: 'Don\'t wish it were easier. Wish you were better.', author: 'Jim Rohn' },
  { text: 'What seems impossible today will one day become your warm-up.', author: 'Unknown' },
  { text: 'The last three or four reps is what makes the muscle grow.', author: 'Arnold Schwarzenegger' },
  { text: 'Strength does not come from winning. Your struggles develop your strengths.', author: 'Arnold Schwarzenegger' },
  { text: 'The difference between the impossible and the possible lies in a person\'s determination.', author: 'Tommy Lasorda' },
  { text: 'Once you are exercising regularly, the hardest thing is to stop it.', author: 'Erin Gray' },
  { text: 'Your body can stand almost anything. It\'s your mind that you have to convince.', author: 'Unknown' },
  { text: 'When you feel like quitting, think about why you started.', author: 'Unknown' },
  { text: 'Champions aren\'t made in the gyms. Champions are made from something they have deep inside them — a desire, a dream, a vision.', author: 'Muhammad Ali' },
  { text: 'I hated every minute of training, but I said, "Don\'t quit. Suffer now and live the rest of your life as a champion."', author: 'Muhammad Ali' },
  { text: 'Discipline is choosing between what you want now and what you want most.', author: 'Abraham Lincoln' },
  { text: 'It never gets easier, you just get stronger.', author: 'Unknown' },
  { text: 'The only way to define your limits is by going beyond them.', author: 'Arthur C. Clarke' },
]
